export const CLI_PARSE_OPTIONS = {
    format: { type: "string", short: "f", default: "json" },
    output: { type: "string", short: "o" },
    "fail-on": { type: "string" },
    locale: { type: "string", default: "en" },
    "scoring-mode": { type: "string", default: "normal" },
    browser: { type: "string" },
    "wait-for": { type: "string" },
    "compare-with": { type: "string" },
    "comparison-output": { type: "string" },
    "comparison-summary-output": { type: "string" },
    "github-actions-summary-output": { type: "string" },
    "gitlab-summary-output": { type: "string" },
    "comparison-ci-json-output": { type: "string" },
    "min-score-delta": { type: "string" },
    "max-critical-increase": { type: "string" },
    "max-warning-increase": { type: "string" },
    "max-recommendation-increase": { type: "string" },
    help: { type: "boolean", short: "h", default: false },
} as const;
