export const RULE_TOKENS_COMPACT: Record<string, string> = {
    "ACC-01": "missing:html lang",
    "ACC-02": "img-missing:alt",
    "ACC-03": "missing:link accessible name",
    "ACC-04": "missing:button accessible name",
    "ACC-05": "missing:control id or name",
    "ACC-06": "missing:label for",
    "ACC-07": "missing:control label",
    "ACC-09": "missing:H1",
    "ACC-10": "jump:heading order",
    "ACC-11": "invalid:aria-labelledby",
    "ACC-12": "invalid:aria-describedby",
    "ACC-13": "positive:tabindex",
    "ACC-14": "nested:interactive",
    "ACC-15": "missing:iframe title",
    "ACC-16": "missing:video controls",
    "ACC-17": "missing:table caption",
    "ACC-18": "missing:th scope",
    "ACC-19": "vague:link text",
    "ACC-20": "missing:link href",
    "ACC-21": "focus:not visible",
    "ACC-22": "text:too small",
    "ACC-23": "duplicate:ids",
    "ACC-24": "missing:skip link",
    "ACC-25": "insufficient:contrast",
    "ACC-26": "low:line-height",
    "SEO-01": "missing:title",
    "SEO-02": "weak:description",
    "SEO-03": "missing:charset",
    "SEO-05": "missing:canonical",
    "SEO-06": "noindex:robots",
    "SEO-07": "missing:open graph",
    "SEO-08": "missing:twitter card",
    "SEO-09": "conflict:canonical",
    "SEO-10": "invalid:hreflang",
    "SEC-01": "unsafe:target=_blank",
    "SEM-01": "use:strong/em",
    "SEM-02": "low:semantic structure",
    "SEM-03": "multiple:h1",
    "SEM-04": "missing:main element",
    "SEM-05": "multiple:main elements",
    "SEM-06": "missing:nav list",
    "SEM-07": "false:list structure",
    "RWD-01": "large:fixed width",
    "RWD-02": "missing:viewport",
    "RWD-03": "overflow:horizontal",
    "RWD-04": "overlap:fixed element",
    "RWD-05": "problematic:100vh",
    "QLT-01": "many:inline styles",
    "QLT-02": "dummy:link",
    "IMG-01": "img-missing:dimensions",
    "IMG-02": "img-missing:lazy loading",
    "IMG-03": "img-missing:async decode",
    "MEDIA-01": "autoplay:no muted",
    "FORM-01": "submit:outside form",
    "FORM-02": "required:no indicator",
    "FORM-03": "missing:email/tel type",
    "FORM-04": "missing:autocomplete",
    "PERF-01": "img-missing:srcset/sizes",
    "PERF-02": "many:fonts/weights",
    "PERF-03": "many:scripts",
    "PERF-04": "missing:script defer in head",
    "PERF-05": "blocking:render css",
    "PERF-06": "missing:cache headers",
    "PERF-09": "missing:fetchpriority",
    "PERF-10": "excess:third-party scripts"
};