import type { IssueCategory, Severity } from "../core/types";

export const CATEGORY_TITLES: Record<IssueCategory, string> = {
    accessibility: "Accessibility",
    semantic: "Semantic",
    seo: "SEO",
    responsive: "Responsive",
    security: "Security",
    quality: "Quality",
    performance: "Performance",
    form: "Forms"
};

export const getCategoryTitle = (cat: IssueCategory): string => CATEGORY_TITLES[cat];

export const CATEGORY_ORDER: IssueCategory[] = ["accessibility", "semantic", "seo", "responsive", "security", "quality", "performance", "form"];

export const CATEGORY_SHORT_LABELS: Record<IssueCategory, string> = {
    accessibility: "ACC",
    semantic: "SEM",
    seo: "SEO",
    responsive: "RWD",
    security: "SEC",
    quality: "QLT",
    performance: "PERF",
    form: "FORM"
};

export const ELEMENTS_EXPORT_LIMIT = 20;
export const ELEMENTS_TXT_PREVIEW_LIMIT = 3;

export const RULE_TOKENS_COMPACT: Record<string, string> = {
    "ACC-01": "missing:html lang",
    "ACC-02": "img-missing:alt",
    "ACC-03": "missing:link accessible name",
    "ACC-04": "missing:button accessible name",
    "ACC-05": "missing:control id or name",
    "ACC-06": "missing:label for",
    "ACC-07": "missing:control label",
    "ACC-09": "missing:H1",
    "ACC-10": "jump:heading order",
    "ACC-11": "invalid:aria-labelledby",
    "ACC-12": "invalid:aria-describedby",
    "ACC-13": "positive:tabindex",
    "ACC-14": "nested:interactive",
    "ACC-15": "missing:iframe title",
    "ACC-16": "missing:video controls",
    "ACC-17": "missing:table caption",
    "ACC-18": "missing:th scope",
    "ACC-19": "vague:link text",
    "ACC-20": "missing:link href",
    "ACC-21": "focus:not visible",
    "ACC-22": "text:too small",
    "ACC-23": "duplicate:ids",
    "ACC-24": "missing:skip link",
    "ACC-25": "insufficient:contrast",
    "ACC-26": "low:line-height",
    "SEO-01": "missing:title",
    "SEO-02": "weak:description",
    "SEO-03": "missing:charset",
    "SEO-05": "missing:canonical",
    "SEO-06": "noindex:robots",
    "SEO-07": "missing:open graph",
    "SEO-08": "missing:twitter card",
    "SEC-01": "unsafe:target=_blank",
    "SEM-01": "use:strong/em",
    "SEM-02": "low:semantic structure",
    "SEM-03": "multiple:h1",
    "SEM-04": "missing:main element",
    "SEM-05": "multiple:main elements",
    "SEM-06": "missing:nav list",
    "SEM-07": "false:list structure",
    "RWD-01": "large:fixed width",
    "RWD-02": "missing:viewport",
    "RWD-03": "overflow:horizontal",
    "RWD-04": "overlap:fixed element",
    "RWD-05": "problematic:100vh",
    "QLT-01": "many:inline styles",
    "QLT-02": "dummy:link",
    "IMG-01": "img-missing:dimensions",
    "IMG-02": "img-missing:lazy loading",
    "IMG-03": "img-missing:async decode",
    "MEDIA-01": "autoplay:no muted",
    "FORM-01": "submit:outside form",
    "FORM-02": "required:no indicator",
    "FORM-03": "missing:email/tel type",
    "FORM-04": "missing:autocomplete",
    "PERF-01": "img-missing:srcset/sizes",
    "PERF-02": "many:fonts/weights",
    "PERF-03": "many:scripts",
    "PERF-04": "missing:script defer in head",
    "PERF-05": "blocking:render css",
    "PERF-06": "missing:cache headers"
};

export const RULE_DESCRIPTIONS: Partial<Record<string, string>> = {
    "ACC-01": "Ensures the HTML element includes a valid lang attribute for language identification",
    "ACC-02": "Ensures all meaningful images have non-empty alt text for screen readers",
    "ACC-07": "Ensures every form control has an accessible label",
    "ACC-09": "Detects pages missing an H1 heading as the primary page title",
    "ACC-10": "Ensures heading levels follow a consistent hierarchical order without skipping levels",
    "ACC-11": "Ensures aria-labelledby references existing element IDs with meaningful text",
    "ACC-12": "Ensures aria-describedby references existing element IDs",
    "ACC-15": "Ensures every iframe has a descriptive title attribute",
    "ACC-21": "Ensures interactive elements have visible focus indicators",
    "ACC-23": "Ensures all DOM element IDs are unique across the document",
    "ACC-25": "Detects text with insufficient contrast ratio against its background",
    "SEC-01": "Detects links with target=_blank missing rel=\"noopener noreferrer\"",
    "SEO-01": "Detects missing or empty page title element",
    "SEM-04": "Detects pages missing a main landmark element to identify primary content",
    "SEM-05": "Detects pages with more than one main landmark element",
    "RWD-02": "Detects missing viewport meta tag required for responsive display on mobile",
    "RWD-05": "Warns about 100vh usage which can cause issues on mobile",
    "FORM-01": "Detects submit buttons placed outside their associated form element",
    "FORM-04": "Detects common form fields missing autocomplete attributes",
    "IMG-01": "Detects images missing width and height attributes that prevent layout shifts",
    "IMG-02": "Detects images below the fold not using lazy loading",
    "PERF-05": "Detects render-blocking CSS in head without preload",
    "PERF-06": "Warns when Cache-Control headers may not be configured"
};

export const RULE_WHY: Partial<Record<string, string>> = {
    "ACC-01": "Screen readers, translation tools, and search engines use the lang attribute to process page content correctly",
    "ACC-02": "Screen reader users cannot understand the purpose of images without alternative text",
    "ACC-07": "Screen reader and keyboard users rely on labels to understand the purpose of form inputs",
    "ACC-09": "The H1 establishes the primary topic of the page for screen readers, search engines, and document outline tools",
    "ACC-10": "Screen reader users navigate pages by heading structure; skipping levels breaks the logical document outline",
    "ACC-11": "Screen readers announce the accessible name using aria-labelledby; a broken reference leaves the element unnamed",
    "ACC-12": "Screen readers read the referenced description when a user focuses an element; broken references silently remove that context",
    "ACC-15": "Screen readers announce the iframe title when users navigate into it; without one, the embedded content has no accessible name",
    "ACC-21": "Keyboard and switch users need visible focus indicators to navigate and understand their current position on the page",
    "ACC-23": "Duplicate IDs break label associations, ARIA references, and scripted behavior that depend on unique element identifiers",
    "ACC-25": "Users with low vision or color blindness may be unable to read text that lacks sufficient contrast",
    "SEC-01": "A page opened via target=_blank can access the opener window object, enabling tabnabbing and phishing attacks",
    "SEO-01": "Search engines use the page title as the primary result label; browsers display it in the tab and in bookmarks",
    "SEM-04": "Assistive technologies and search engines use the main landmark to locate and describe the primary content of a page",
    "SEM-05": "Multiple main elements create an ambiguous document structure that confuses assistive technologies and search engines",
    "RWD-02": "Without a viewport meta tag, mobile browsers render pages at desktop width, making content visually unusable on small screens",
    "FORM-01": "A submit button outside its form does not trigger submission by default, breaking the form for keyboard and assistive technology users",
    "FORM-04": "Autocomplete reduces input errors and speeds up form completion, which is especially critical for users with motor difficulties or dyslexia",
    "IMG-01": "Browsers need image dimensions to reserve layout space during load; missing dimensions cause Cumulative Layout Shift (CLS)",
    "IMG-02": "Loading all images on page load increases initial bytes transferred, delays Time to Interactive, and wastes bandwidth on unseen content"
};

export const RULE_STANDARD_TYPE: Partial<Record<string, "wcag" | "html-spec" | "owasp" | "web-dev" | "heuristic">> = {
    "ACC-01": "wcag",
    "ACC-02": "wcag",
    "ACC-07": "wcag",
    "ACC-09": "heuristic",
    "ACC-10": "wcag",
    "ACC-11": "wcag",
    "ACC-12": "wcag",
    "ACC-15": "wcag",
    "ACC-21": "wcag",
    "ACC-23": "html-spec",
    "ACC-25": "wcag",
    "SEC-01": "owasp",
    "SEO-01": "html-spec",
    "SEM-04": "heuristic",
    "SEM-05": "heuristic",
    "RWD-02": "html-spec",
    "FORM-01": "html-spec",
    "FORM-04": "wcag",
    "IMG-01": "web-dev",
    "IMG-02": "web-dev"
};

export const RULE_STANDARD_LABEL: Partial<Record<string, string>> = {
    "ACC-01": "WCAG 2.1 — 3.1.1 Language of Page",
    "ACC-02": "WCAG 2.1 — 1.1.1 Non-text Content",
    "ACC-07": "WCAG 2.1 — 1.3.1 Info and Relationships",
    "ACC-09": "Best practice — page heading structure",
    "ACC-10": "WCAG 2.1 — 1.3.1 Info and Relationships",
    "ACC-11": "WCAG 2.1 — 1.3.1 Info and Relationships",
    "ACC-12": "WCAG 2.1 — 1.3.1 Info and Relationships",
    "ACC-15": "WCAG 2.1 — 2.4.1 Bypass Blocks",
    "ACC-21": "WCAG 2.1 — 2.4.7 Focus Visible",
    "ACC-23": "HTML spec — id attribute uniqueness",
    "ACC-25": "WCAG 2.1 — 1.4.3 Contrast (Minimum)",
    "SEC-01": "OWASP — Reverse Tabnapping",
    "SEO-01": "HTML spec — title element",
    "SEM-04": "HTML5 best practice — main landmark",
    "SEM-05": "HTML5 best practice — main landmark",
    "RWD-02": "HTML spec — viewport meta tag",
    "FORM-01": "HTML spec — form submission",
    "FORM-04": "WCAG 2.1 — 1.3.5 Identify Input Purpose",
    "IMG-01": "Core Web Vitals — Cumulative Layout Shift (CLS)",
    "IMG-02": "web.dev — loading performance"
};

export const RULE_DOCS_SLUG: Partial<Record<string, string>> = {
    "ACC-01": "ACC-01",
    "ACC-02": "ACC-02",
    "ACC-07": "ACC-07",
    "ACC-09": "ACC-09",
    "ACC-10": "ACC-10",
    "ACC-11": "ACC-11",
    "ACC-12": "ACC-12",
    "ACC-15": "ACC-15",
    "ACC-21": "ACC-21",
    "ACC-23": "ACC-23",
    "ACC-25": "ACC-25"
};

export const RULE_FIXES: Record<string, string> = {
    "ACC-01": "Set a valid document language: add lang to the html element, e.g. <html lang=\"en\">.",
    "ACC-02": "Add descriptive alt text to informative images, or alt=\"\" for decorative images.",
    "ACC-03": "Ensure each link has an accessible name using visible text, aria-label, or labelled content.",
    "ACC-04": "Give buttons an accessible name via text content, aria-label, or aria-labelledby.",
    "ACC-05": "Add stable id or name attributes to form controls so labels and scripts can target them.",
    "ACC-06": "Associate labels with controls using for/id, or wrap the input inside its label.",
    "ACC-07": "Provide a visible label (or aria-label/aria-labelledby) for each form control.",
    "ACC-09": "Add an H1 to the page as the main heading for better structure and accessibility.",
    "ACC-10": "Use headings in order (H1 → H2 → H3) and avoid skipping levels.",
    "ACC-11": "Update aria-labelledby to reference existing element IDs with meaningful text.",
    "ACC-12": "Update aria-describedby to reference existing IDs that contain helpful descriptions.",
    "ACC-13": "Remove positive tabindex values; use tabindex=\"0\" for focusable custom controls or tabindex=\"-1\" for programmatic focus.",
    "ACC-14": "Do not nest interactive elements; keep one interactive control per clickable region.",
    "ACC-15": "Add a concise and descriptive title attribute to each iframe.",
    "ACC-16": "Add controls attribute to video elements without autoplay or muted attributes.",
    "ACC-17": "Add a caption element or aria-label to describe the table's purpose.",
    "ACC-18": "Add scope=\"row\" or scope=\"col\" to th elements for better screen reader support.",
    "ACC-19": "Replace vague link text with specific action/context (avoid 'click here' patterns).",
    "ACC-20": "Provide a valid href for anchors, or use a button element for non-navigation actions.",
    "ACC-21": "Remove outline: none rules or provide alternative focus indicators via box-shadow, border, or background changes.",
    "ACC-22": "Increase text size to meet readability targets and avoid very small default font sizes.",
    "ACC-23": "Ensure every id is unique across the DOM to prevent broken references.",
    "ACC-24": "Add a skip link near the top of the page to allow keyboard users to jump to main content.",
    "ACC-25": "Increase color contrast by darkening text, lightening backgrounds, or adjusting both to meet WCAG AA (4.5:1) or AAA (7:1).",
    "ACC-26": "Increase line-height to at least 1.4 (or 1.5x font size) to improve text readability and spacing.",
    "SEO-01": "Add a descriptive <title> element in the document <head>.",
    "SEO-02": "Add a meta description tag with a concise summary of the page content.",
    "SEO-03": "Add <meta charset=\"UTF-8\"> in the <head> to declare document encoding.",
    "SEO-05": "Add a canonical link tag to specify the preferred URL for this page.",
    "SEO-06": "Remove or revise meta robots noindex directive to allow search engine indexing.",
    "SEO-07": "Add Open Graph meta tags (og:title, og:description, og:image) for better social sharing.",
    "SEO-08": "Add Twitter Card meta tags (twitter:card, twitter:title, twitter:description) for better Twitter sharing.",
    "SEC-01": "For target=_blank links, include rel=\"noopener noreferrer\" to block tabnabbing.",
    "SEM-01": "Use semantic elements like <strong> instead of <b>, and <em> instead of <i> for better meaning.",
    "SEM-02": "Improve semantic structure by using appropriate HTML5 elements (header, nav, main, article, section, aside, footer).",
    "SEM-03": "Use only one H1 per page as the primary heading.",
    "SEM-04": "Add a <main> element to identify the primary content area of the page.",
    "SEM-05": "Use only one <main> element per page.",
    "SEM-06": "Wrap navigation links inside a list (ul/ol) for better structure and accessibility.",
    "SEM-07": "Replace non-list children (like divs) with proper <li> elements inside ul/ol.",
    "RWD-01": "Use relative units (%, rem, em) or max-width instead of fixed pixel widths.",
    "RWD-02": "Add a viewport meta tag: <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.",
    "RWD-03": "Fix horizontal overflow by removing fixed widths or using max-width with overflow-x: hidden.",
    "RWD-04": "Reduce the height of fixed/sticky elements or ensure they don't obstruct important content.",
    "RWD-05": "Use 100% or min(100vh, 100%) instead of 100vh, or use viewport-relative units that account for address bars.",
    "QLT-01": "Move inline styles to external CSS files or style blocks for better maintainability.",
    "QLT-02": "Replace dummy href=\"#\" with proper URLs or convert to buttons for actions.",
    "IMG-01": "Add width and height attributes to images to prevent layout shifts.",
    "IMG-02": "Add loading=\"lazy\" to images below the fold for better performance.",
    "IMG-03": "Add decoding=\"async\" to images for non-blocking rendering.",
    "MEDIA-01": "Add muted attribute to videos with autoplay to comply with browser autoplay policies.",
    "FORM-01": "Place submit buttons inside their form or bind them with the form attribute.",
    "FORM-02": "Indicate required fields visually in the label (e.g., with * or \"(required)\").",
    "FORM-03": "Use type=\"email\" for email inputs and type=\"tel\" for phone inputs for better validation and mobile keyboards.",
    "FORM-04": "Add autocomplete attributes to common fields (name, email, tel, etc.) for better UX.",
    "PERF-01": "Add srcset and sizes attributes to provide responsive images for different screen sizes.",
    "PERF-02": "Reduce the number of font families and weights; consider using system fonts.",
    "PERF-03": "Bundle scripts or remove unused dependencies to reduce HTTP requests.",
    "PERF-04": "Add defer or async attributes to scripts in <head> to avoid blocking page rendering.",
    "PERF-05": "Inline critical CSS or use preload for CSS; consider async loading non-critical styles.",
    "PERF-06": "Configure server Cache-Control headers or use CDN edge caching for static assets."
};

export const CATEGORY_PREFIXES: Partial<Record<IssueCategory, string[]>> = {
    accessibility: ["ACC"],
    semantic: ["SEM"],
    seo: ["SEO"],
    responsive: ["RWD"],
    security: ["SEC"],
    quality: ["QLT", "UX"],
    performance: ["PERF", "IMG", "MEDIA"],
    form: ["FORM"]
};

export const SEVERITY_RANK: Record<Severity, number> = {
    recommendation: 1,
    warning: 2,
    critical: 3
};

export const WAH_VERSION = typeof __WAH_VERSION__ !== "undefined" ? __WAH_VERSION__ : "0.0.0-dev";
export const WAH_MODE: "dev" | "ci" = typeof __WAH_MODE__ !== "undefined" && __WAH_MODE__ === "ci" ? "ci" : "dev";