import type { IssueCategory, Severity } from "../core/types";

export const getCategoryTitle = (cat: IssueCategory): string => {
    const titles: Record<IssueCategory, string> = {
        accessibility: "Accessibility",
        semantic: "Semantic",
        seo: "SEO",
        responsive: "Responsive",
        security: "Security",
        quality: "Quality",
        performance: "Performance",
        form: "Forms"
    };
    return titles[cat];
};

export const CATEGORY_TITLES: Record<IssueCategory, string> = {
    accessibility: "Accessibility",
    semantic: "Semantic",
    seo: "SEO",
    responsive: "Responsive",
    security: "Security",
    quality: "Quality",
    performance: "Performance",
    form: "Forms"
};

export const CATEGORY_ORDER: IssueCategory[] = ["accessibility", "semantic", "seo", "responsive", "security", "quality", "performance", "form"];

export const CATEGORY_SHORT_LABELS: Record<IssueCategory, string> = {
    accessibility: "ACC",
    semantic: "SEM",
    seo: "SEO",
    responsive: "RWD",
    security: "SEC",
    quality: "QLT",
    performance: "PERF",
    form: "FORM"
};

export const ELEMENTS_EXPORT_LIMIT = 20;
export const ELEMENTS_TXT_PREVIEW_LIMIT = 3;

export const RULE_TITLES: Record<string, string> = {
    "ACC-01": "Missing html lang",
    "ACC-02": "Image missing alt",
    "ACC-03": "Link missing accessible name",
    "ACC-04": "Button missing accessible name",
    "ACC-05": "Control missing id or name",
    "ACC-06": "Label missing for",
    "ACC-07": "Control missing label",
    "ACC-09": "Missing H1",
    "ACC-10": "Heading order jump",
    "ACC-11": "aria-labelledby invalid",
    "ACC-12": "aria-describedby invalid",
    "ACC-13": "Positive tabindex",
    "ACC-14": "Nested interactive",
    "ACC-15": "Iframe missing title",
    "ACC-16": "Video missing controls",
    "ACC-17": "Table missing caption",
    "ACC-18": "TH missing scope",
    "ACC-19": "Vague link text",
    "ACC-20": "Link missing href",
    "ACC-21": "Focus not visible",
    "ACC-22": "Text too small",
    "ACC-23": "Duplicate IDs",
    "ACC-24": "Missing skip link",
    "ACC-25": "Insufficient contrast",
    "ACC-26": "Line-height too low",
    "SEO-01": "Missing title",
    "SEO-02": "Weak or missing description",
    "SEO-03": "Missing charset",
    "SEO-05": "Missing canonical",
    "SEO-06": "Robots noindex",
    "SEO-07": "Missing Open Graph",
    "SEO-08": "Missing Twitter Card",
    "SEC-01": "Unsafe target=_blank",
    "SEM-01": "Use strong/em",
    "SEM-02": "Low semantic structure",
    "SEM-03": "Multiple H1",
    "SEM-04": "Missing main element",
    "SEM-05": "Multiple main elements",
    "SEM-06": "Nav missing list",
    "SEM-07": "False list structure",
    "RWD-01": "Large fixed width",
    "RWD-02": "Missing viewport",
    "RWD-03": "Horizontal overflow",
    "RWD-04": "Fixed element overlap",
    "RWD-05": "Problematic 100vh",
    "QLT-01": "Too many inline styles",
    "QLT-02": "Dummy link",
    "IMG-01": "Image missing dimensions",
    "IMG-02": "Image missing lazy loading",
    "IMG-03": "Image missing async decode",
    "MEDIA-01": "Autoplay without muted",
    "FORM-01": "Submit button outside form",
    "FORM-02": "Required without indicator",
    "FORM-03": "Email/tel without type",
    "FORM-04": "Missing autocomplete",
    "PERF-01": "Image missing srcset/sizes",
    "PERF-02": "Too many fonts/weights",
    "PERF-03": "Too many scripts",
    "PERF-04": "Script without defer in head",
    "PERF-05": "Render-blocking CSS",
    "PERF-06": "Missing cache headers"
};

export const RULE_DESCRIPTIONS: Partial<Record<string, string>> = {
    "ACC-01": "Ensures the <html> element includes a valid lang attribute",
    "ACC-02": "Ensures meaningful images include a non-empty alt attribute",
    "ACC-03": "Ensures links expose an accessible name",
    "ACC-04": "Ensures buttons expose an accessible name",
    "ACC-05": "Ensures form controls provide an id or name",
    "ACC-06": "Ensures labels include a valid for association",
    "ACC-07": "Ensures form controls are properly labeled",
    "ACC-09": "Ensures the page includes a primary H1 heading",
    "ACC-10": "Ensures headings follow a consistent hierarchical order",
    "ACC-11": "Ensures aria-labelledby references existing elements",
    "ACC-12": "Ensures aria-describedby references existing elements",
    "ACC-13": "Ensures tabindex values are not positive",
    "ACC-14": "Ensures interactive elements are not nested",
    "ACC-15": "Ensures iframes include a descriptive title",
    "ACC-16": "Ensures videos provide native controls",
    "ACC-17": "Ensures tables include a caption",
    "ACC-18": "Ensures table header cells include proper scope",
    "ACC-19": "Ensures link text is specific and descriptive",
    "ACC-20": "Ensures anchor elements include an href attribute",
    "ACC-21": "Ensures interactive elements have visible focus indicators",
    "ACC-22": "Ensures text size meets minimum readability thresholds",
    "ACC-23": "Ensures DOM ids are unique",
    "ACC-24": "Ensures skip links are available for keyboard navigation",
    "ACC-25": "Ensures text has sufficient contrast with its background",
    "ACC-26": "Ensures line-height provides adequate spacing for readability",
    "SEO-01": "Ensures the page has a valid <title>",
    "SEO-02": "Ensures the page includes a useful meta description",
    "SEO-03": "Ensures a charset meta tag is declared",
    "SEO-05": "Ensures a canonical link is present",
    "SEO-06": "Ensures robots metadata does not unintentionally block indexing",
    "SEO-07": "Ensures Open Graph metadata is present",
    "SEO-08": "Ensures Twitter Card metadata is present",
    "SEC-01": "Ensures target=_blank links include rel=noopener",
    "SEM-01": "Encourages semantic emphasis tags over presentational tags",
    "SEM-02": "Detects weak semantic structure in page layout",
    "SEM-03": "Ensures only one H1 is used for the main page heading",
    "SEM-04": "Ensures main element is present for page content",
    "SEM-05": "Ensures only one main element exists",
    "SEM-06": "Ensures nav elements contain list structures",
    "SEM-07": "Ensures proper list markup is used",
    "RWD-01": "Detects oversized fixed-width elements that hurt responsiveness",
    "RWD-02": "Ensures a viewport meta tag is configured",
    "RWD-03": "Detects horizontal scrolling caused by overflowing content",
    "RWD-04": "Ensures fixed elements do not cover excessive viewport area",
    "RWD-05": "Warns about 100vh usage which can cause issues on mobile",
    "QLT-01": "Detects excessive use of inline styles",
    "QLT-02": "Detects links that use dummy href values",
    "IMG-01": "Ensures images include height and width attributes",
    "IMG-02": "Ensures below-fold images use lazy loading",
    "IMG-03": "Encourages async decoding attribute for images",
    "MEDIA-01": "Ensures autoplay videos have muted attribute",
    "FORM-01": "Ensures submit buttons are inside form elements",
    "FORM-02": "Ensures required fields are visually indicated",
    "FORM-03": "Ensures email and tel inputs use correct types",
    "FORM-04": "Encourages autocomplete attributes on form fields",
    "PERF-01": "Encourages responsive images with srcset and sizes",
    "PERF-02": "Warns about excessive font resources that slow page load",
    "PERF-03": "Detects excessive script tags that may block rendering",
    "PERF-04": "Ensures scripts in head use defer or async attributes",
    "PERF-05": "Detects render-blocking CSS in head without preload",
    "PERF-06": "Warns when Cache-Control headers may not be configured"
};

export const RULE_FIXES: Partial<Record<string, string>> = {
    "ACC-01": "Set a valid document language: add lang to the html element, e.g. <html lang=\"en\">.",
    "ACC-02": "Add descriptive alt text to informative images, or alt=\"\" for decorative images.",
    "ACC-03": "Ensure each link has an accessible name using visible text, aria-label, or labelled content.",
    "ACC-04": "Give buttons an accessible name via text content, aria-label, or aria-labelledby.",
    "ACC-05": "Add stable id or name attributes to form controls so labels and scripts can target them.",
    "ACC-06": "Associate labels with controls using for/id, or wrap the input inside its label.",
    "ACC-07": "Provide a visible label (or aria-label/aria-labelledby) for each form control.",
    "ACC-09": "Add exactly one meaningful H1 that describes the main purpose of the page.",
    "ACC-10": "Use headings in order (H1 → H2 → H3) and avoid skipping levels.",
    "ACC-11": "Update aria-labelledby to reference existing element IDs with meaningful text.",
    "ACC-12": "Update aria-describedby to reference existing IDs that contain helpful descriptions.",
    "ACC-13": "Avoid positive tabindex; keep natural DOM order or use tabindex=\"0\" when needed.",
    "ACC-14": "Do not nest interactive elements; keep one interactive control per clickable region.",
    "ACC-15": "Add a concise and descriptive title attribute to each iframe.",
    "ACC-16": "Enable video controls or provide equivalent custom controls with keyboard support.",
    "ACC-17": "Add a caption to each data table to describe its purpose.",
    "ACC-18": "Set proper scope on TH cells (col, row, colgroup, rowgroup) based on table structure.",
    "ACC-19": "Replace vague link text with specific action/context (avoid 'click here' patterns).",
    "ACC-20": "Provide a valid href for anchors, or use a button element for non-navigation actions.",
    "ACC-21": "Remove outline: none rules or provide alternative focus indicators via box-shadow, border, or background changes.",
    "ACC-22": "Increase text size to meet readability targets and avoid very small default font sizes.",
    "ACC-23": "Ensure every id is unique across the DOM to prevent broken references.",
    "ACC-24": "Add a visible-on-focus skip link pointing to your main content container.",
    "ACC-25": "Increase color contrast by darkening text, lightening backgrounds, or adjusting both to meet WCAG AA (4.5:1) or AAA (7:1).",
    "ACC-26": "Increase line-height to at least 1.4 (or 1.5x font size) to improve text readability and spacing.",
    "SEO-01": "Set a unique, descriptive title with primary keywords near the start.",
    "SEO-02": "Add a concise meta description that summarizes page intent and encourages clicks.",
    "SEO-03": "Declare charset early in head, e.g. <meta charset=\"utf-8\">.",
    "SEO-05": "Add a canonical link element pointing to the preferred URL of the page.",
    "SEO-06": "Review robots directives and remove noindex when indexing is intended.",
    "SEO-07": "Add Open Graph tags (title, description, image, url) for social previews.",
    "SEO-08": "Add Twitter Card metadata (card, title, description, image) for link sharing.",
    "SEC-01": "For target=_blank links, include rel=\"noopener noreferrer\" to block tabnabbing.",
    "SEM-01": "Prefer semantic emphasis tags (strong/em) instead of purely presentational b/i.",
    "SEM-02": "Use semantic layout landmarks (main, header, nav, section, article, footer) where relevant.",
    "SEM-03": "Keep a single H1 and move other top-level headings to H2/H3 as needed.",
    "SEM-04": "Wrap primary page content in one main element.",
    "SEM-05": "Keep only one main element per page and move secondary regions to section/article.",
    "SEM-06": "Ensure nav landmarks contain structured lists of navigation links.",
    "SEM-07": "Use real ul/ol/li list markup instead of div/span groups that mimic lists.",
    "RWD-01": "Replace large fixed widths with fluid sizing (%, max-width, clamp) and responsive breakpoints.",
    "RWD-02": "Add a proper viewport meta tag, e.g. width=device-width, initial-scale=1.",
    "RWD-03": "Use fluid layouts, max-width constraints, or media queries to prevent horizontal scrolling.",
    "RWD-04": "Reduce fixed element height or make it scrollable internally to avoid covering main content.",
    "RWD-05": "Use 100% or min(100vh, 100%) instead of 100vh, or use viewport-relative units that account for address bars.",
    "QLT-01": "Move repeated inline styles to CSS classes and central stylesheets.",
    "QLT-02": "Replace dummy href values with real destinations or use buttons for JS-only actions.",
    "IMG-01": "Set explicit width and height attributes to reduce layout shift.",
    "IMG-02": "Use loading=\"lazy\" for below-the-fold images.",
    "IMG-03": "Use decoding=\"async\" for non-critical images.",
    "MEDIA-01": "When autoplay is needed, also set muted (and usually playsinline) on video.",
    "FORM-01": "Place submit buttons inside their form or bind them with the form attribute.",
    "FORM-02": "Visually indicate required fields and keep required attributes consistent with UI.",
    "FORM-03": "Use semantic input types (email/tel) to improve validation and mobile keyboards.",
    "FORM-04": "Add meaningful autocomplete values to common form fields.",
    "PERF-01": "Use srcset and sizes attributes for responsive images to serve appropriately sized assets.",
    "PERF-02": "Limit font families and weights; consider using system fonts or variable fonts.",
    "PERF-03": "Consolidate scripts or use module bundlers to reduce HTTP requests and blocking.",
    "PERF-04": "Add defer or async to scripts in head to prevent render blocking.",
    "PERF-05": "Inline critical CSS or use preload for CSS; consider async loading non-critical styles.",
    "PERF-06": "Configure server Cache-Control headers or use CDN edge caching for static assets."
};

export const CATEGORY_PREFIXES: Partial<Record<IssueCategory, string[]>> = {
    accessibility: ["ACC"],
    semantic: ["SEM"],
    seo: ["SEO"],
    responsive: ["RWD"],
    security: ["SEC"],
    quality: ["QLT"],
    performance: ["PERF", "IMG", "MEDIA"],
    form: ["FORM"]
};

export const SEVERITY_RANK: Record<Severity, number> = {
    recommendation: 1,
    warning: 2,
    critical: 3
};

export const WAH_VERSION = typeof __WAH_VERSION__ !== "undefined" ? __WAH_VERSION__ : "0.0.0-dev";
export const WAH_MODE: "dev" | "ci" = typeof __WAH_MODE__ !== "undefined" && __WAH_MODE__ === "ci" ? "ci" : "dev";